services:
  # MongoDB Service
  - type: pserv
    name: mongodb
    env: docker
    disk:
      name: mongodb_data
      mountPath: /data/db
      sizeGB: 10
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        sync: false
      - key: MONGO_INITDB_ROOT_PASSWORD
        sync: false

  # Backend API Service
  - type: web
    name: api
    env: docker
    buildCommand: docker build -t api ./nestjs-api
    envVars:
      - key: DATABASE_URL
        value: mongodb://mongodb:27017
      - key: KAFKA_BROKERS
        value: "kafka:9092"

  # Go Microservice
  - type: web
    name: broker
    env: docker
    buildCommand: docker build -t broker ./go-homebroker-simulator
    envVars:
      - key: KAFKA_BROKERS
        value: "kafka:9092"

  # Frontend Service
  - type: web
    name: frontend
    env: docker
    buildCommand: docker build -t frontend ./next-frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://api.onrender.com
      - key: NEXT_PUBLIC_BROKER_URL
        value: https://broker.onrender.com

  # Kafka Service
  - type: pserv
    name: kafka
    env: docker
    disk:
      name: kafka_data
      mountPath: /var/lib/kafka/data
      sizeGB: 10
